### ISSUE TITLE
Is this still only for classic or is there a Retail Version yet?

### ISSUE THREAD

**Issue by Enigma-TL** [Dreamwalker-Collective/faction-friend#47]
Just wondering with Shadowlands on the horizon.

**Comment by ShaunaGordon** [comment]
(Sorry, this apparently got lost in the flood of notifications I received during the last couple of months of 2020.)

Unfortunately, I was never able to get it working again with Retail, due to the interaction between how FactionFriend fundamentally works and the parts that Blizzard locked into their secure functions stuff.

I still plan to do a ground-up new build for Retail, but I'm still in the process of arranging my schedule to be able to accommodate doing so.
